export { queryClient } from './client';
export * from './types';
export { useApiQuery } from './hooks/useApiQuery';
export { useApiInfiniteSelectQuery } from './hooks/useApiInfiniteSelectQuery';
export * from './keys/dictionary';
export * from './keys/users';
export * from './path/dictionary';
export * from './path/user';
export * from './keys/outgoing';
export * from './keys/route';
export * from './path/outgoing';
export * from './path/route';
export { QueryProvider } from './provider';
